# 数据库变量定义
database:
  name: lanb_wvs

server: 
    port: 1234
    tomcat:
      accesslog:
        enabled: true
spring:
  http:  
    encoding: 
      charset: UTF-8
      enabled: true
      force: true
logging:
  file: logs/log.log
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: debug
    com.colodoo: DEBUG

# mybatis配置
mybatis:
  type-aliases-package: org.colodoo.**.model
  mapper-locations: classpath*:**/*Mapper.xml

spring.datasource:
    url: jdbc:mysql://127.0.0.1:3306/${database.name}?characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

#spring.devtools.restart.enabled: true

# 代码生成相关
creater:
  #src-path: E:\dev\project\lanb-wvs\lanb-wvs-be
  table-schema: ${database.name}
  url: ${spring.datasource.url}

# redis配置
spring.redis.host: 127.0.0.1
spring.redis.port: 6379
#spring.redis.database: 1
#spring.redis.timeout: 5000

# 文件大小
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB

#server.session.cookie.comment = ＃注释会话cookie。
#server.session.cookie.domain = ＃会话cookie的域。
#server.session.cookie.http-only =＃“HttpOnly”标志为会话cookie。
#server.session.cookie.max-age = ＃会话cookie的最大年龄（以秒为单位）。
#server.session.cookie.name = ＃会话cookie名称。
#server.session.cookie.path = ＃会话cookie的路径。
#server.session.cookie.secure = ＃“Secure”标志为会话cookie。
#server.session.persistent = false ＃在重新启动之间持续会话数据。
#server.session.store-dir = ＃用于存储会话数据的目录。
#server.session.timeout: 1
#server.session.tracking-modes =＃会话跟踪模式（以下一个或多个：“cookie”，“url”，“ssl”）。

#server.servlet.session.timeout: 1

#rabbitMQ
spring.rabbitmq.host: 192.168.31.129
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest